### PR TITLE
RT-15782 Fallback to default limit

### LINKED ISSUE #13: Exceptions are thrown when using the export option
Hello,

Exceptions are thrown when using the `export` option on the API. 
When using the `export` option, the response is very limited, we only get the fields we ask for. 
It causes errors with some of the object because some fields are required and not expected to be null. 

The problem is similar to #12.

I have noticed the issue when using the `list` option for `contacts` and `domains`. The `limit` field is the one causing the issue. 

```php
// Throw an exception
$rtr->domains->list(parameters: [
    'export' => 'true',
    'fields' => 'createdDate'
]);
```

Capture d’écran_2025-01-02_15-01-53

### PR DESCRIPTION
**Pull request by zbrag**

### CODE REVIEW

**Comment by zbrag** [comment]
Also related to #13

File: src/Api/AbstractApi.php [hunk 1]
```diff
@@ -12,4 +13,37 @@ public function __construct(AuthorizedClient $client)
...
+        }
+        if (! is_null($search)) {
+            $query['q'] = $search;
+        }
+
+        if (! is_null($parameters)) {
+            // Remove this special parameter, it should only be used for the export calls
+            if (array_key_exists('export', $parameters)) {
+                throw new InvalidArgumentException('Export parameter not allowed for this request, use the "export" request.');
+            }
```
Comment (PJEilers) [inline src/Api/AbstractApi.php]: Maybe nitpicking here, but if the export key maps to null or false it shouldnt be a problem

Comment (zbrag) [reply src/Api/AbstractApi.php]: I think I agree with you

File: src/Api/AbstractApi.php [hunk 2]
```diff
@@ -12,4 +13,39 @@ public function __construct(AuthorizedClient $client)
...
+        if (! is_null($search)) {
+            $query['q'] = $search;
+        }
+
+        if (! is_null($parameters)) {
+            // Remove this special parameter, if it's used. It should only be used for the export calls
+            if (
+                array_key_exists('export', $parameters) && (array_key_exists('fields', $parameters) && ! empty($parameters['fields']))
+            ) {
+                throw new InvalidArgumentException('Export parameter not allowed for this request, use the "export" request.');
```
Comment (PJEilers) [inline src/Api/AbstractApi.php]: This not what I meant, you can have an export without fields. In that case, you only get the default fields and the list request will still fail. I meant if you have `"export" => False `or `"export" => null` in your parameters, the request is essentially valid.

**Review by PJEilers — APPROVED** [review]
